#!/bin/bash
# Quick Email Setup - Mailgun (Recommended)

echo "🚀 SiteLedger Email Setup - Mailgun"
echo ""
echo "Step 1: Sign up at https://signup.mailgun.com/new/signup"
echo "  - Use your email (azgharjawazkhan@gmail.com)"
echo "  - Credit card required but won't be charged"
echo "  - 5,000 free emails per month!"
echo ""
echo "Step 2: Get your SMTP credentials"
echo "  1. Go to Dashboard → Sending → Domains"
echo "  2. Click on your sandbox domain"
echo "  3. Click 'SMTP' tab"
echo "  4. Copy the credentials"
echo ""
echo "Step 3: Update your .env file with:"
echo ""
echo "SMTP_HOST=smtp.mailgun.org"
echo "SMTP_PORT=587"
echo "SMTP_USER=postmaster@sandboxXXXXXXXX.mailgun.org"
echo "SMTP_PASS=your-mailgun-password"
echo "SMTP_FROM=\"SiteLedger\" <noreply@sandboxXXXXXXXX.mailgun.org>"
echo ""
echo "Step 4: Restart the server"
echo "  cd /Users/zia/Desktop/SiteLedger/backend"
echo "  kill \$(cat server.pid)"
echo "  node src/index.js > server.log 2>&1 & echo \$! > server.pid"
echo ""
echo "Step 5: Test by inviting a worker!"
echo ""
echo "---"
echo "Why Mailgun?"
echo "✅ 5,000 emails/month (vs Gmail's 500/day)"
echo "✅ Better deliverability"
echo "✅ Perfect for DigitalOcean"
echo "✅ Production ready"
echo "✅ Email analytics"
echo ""
echo "Sign up now: https://signup.mailgun.com/new/signup"
